---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to install CloudWagentAgent on windows. It was validated on windows 2016"
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: "cochlear-sitecore-dev"
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.large
    ConstraintDescription: must be a valid EC2 instance type.
    AllowedValues:
      - t2.micro
      - t1.micro
      - t3.large
  InstanceAMI:
    Description: Managed AMI ID for EC2 Instance
    Type: String
    Default: ami-0efea4c02b339a240
  IAMRole:
    Description: EC2 attached IAM role
    Type: String
    Default: CloudWatchAgentAdminRole
    ConstraintDescription: must be an existing IAM role which will be attached to EC2 instance.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: "9"
    MaxLength: "18"
    Default: 1.43.196.6/32
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Authentication:
        S3BucketAccessCredential:
          type: "S3"
          buckets:
            - cochlear-sitecore-dependency-automation
          roleName: !Ref InstanceRole
      AWS::CloudFormation::Init:
        configSets:
          default:
            - 00_download_qualys_agent
        00_download_qualys_agent:
          files:
            "c:\\squid\\squid.msi":
              source: "https://cochlear-sitecore-dependency-automation.s3-ap-southeast-2.amazonaws.com/squid.msi"
              authentication: S3BucketAccessCredential

          commands:
            01_unzip_qualys_agent:
              cwd: "c:\\squid"
              command: "c:\\squid\\squid.msi"

    Properties:
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile:
        Ref: IAMRoleS3FullAccessInstanceProfile
      KeyName:
        Ref: KeyName
      ImageId:
        Ref: InstanceAMI
      SecurityGroupIds: [!GetAtt NewSecurityGroup.GroupId]
      SubnetId: "subnet-05b6e331718fcde98"
      UserData:
        Fn::Base64: !Sub |
          <script>
            cfn-init.exe -v --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region} --configsets default
            cfn-signal.exe -e %errorlevel% --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}
          </script>
    CreationPolicy:
      ResourceSignal:
        Count: "1"
        Timeout: PT15M
  NewSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable RDP access via port 3389
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 54.153.196.53/32
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: "0.0.0.0/0"
      VpcId: "vpc-0255bccd72bc832f6"

    # S3 Access role
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "S3Download"
      PolicyDocument:
        Statement:
          Action:
            - s3:*
          Effect: Allow
          Resource:
            - arn:aws:s3:::cochlear-sitecore-dependency-automation/*
      Roles:
        - !Ref InstanceRole

  # Instance profile
  IAMRoleS3FullAccessInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref InstanceRole
